import { test } from 'node:test';
import assert from 'node:assert/strict';
import { approvedOnly, filterProducts, purchaseUrl } from '../src/lib/catalog';
import type { Product } from '../src/types/product';
const fixture = (id:string,price:number,status:Product['status']='approved'):Product => ({id,price,status,locale:'ja',name:id,officialName:id,modelNumber:null,brand:'test',category:'Furniture',image:'/test.jpg',shop:'test',officialUrl:'https://example.com/',affiliateUrl:'',affiliateProvider:null,material:'',dimensions:'',tags:[],livingBenefit:'',japandiFit:'',caveats:[],purchaseNotes:{availableInJapan:'',domesticShipping:'',paymentOptions:'',deliveryLeadTime:'',returnCancellationNotes:'',thingsToKnowBeforeBuying:[]},priceCheckedAt:null,isSample:false});
test('candidate is excluded even when it matches filters',()=>{const items=[fixture('public',2999),fixture('private',100,'candidate')];assert.deepEqual(approvedOnly(items).map(p=>p.id),['public']);assert.deepEqual(filterProducts(items,'Furniture','up-to-10000').map(p=>p.id),['public']);assert.equal(purchaseUrl(items[1]),null);});
test('price bands do not overlap at their boundaries',()=>{const items=[fixture('9999',9999),fixture('10000',10000),fixture('10001',10001),fixture('30000',30000),fixture('30001',30001),fixture('100000',100000),fixture('100001',100001)];assert.deepEqual(filterProducts(items,'all','up-to-10000').map(p=>p.id),['9999','10000']);assert.deepEqual(filterProducts(items,'all','10000-30000').map(p=>p.id),['10001','30000']);assert.deepEqual(filterProducts(items,'all','30000-100000').map(p=>p.id),['30001','100000']);assert.deepEqual(filterProducts(items,'all','over-100000').map(p=>p.id),['100001']);});
test('price and category filters combine',()=>{const items=[fixture('furniture',20000),{...fixture('everyday',20000),category:'Everyday' as const}];assert.deepEqual(filterProducts(items,'Furniture','10000-30000').map(p=>p.id),['furniture']);});
test('only an approved product with a safe affiliate URL gets a purchase link',()=>{assert.equal(purchaseUrl({...fixture('sample',100),isSample:true,affiliateUrl:'https://px.a8.net/example'}),null);assert.equal(purchaseUrl({...fixture('missing',100),affiliateUrl:''}),null);assert.equal(purchaseUrl({...fixture('unsafe',100),affiliateUrl:'javascript:alert(1)'}),null);assert.equal(purchaseUrl({...fixture('real',100),affiliateUrl:'https://px.a8.net/example'}),'https://px.a8.net/example');});
